services:
  app:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.5}
        PHALCON_VARIANT: ${PHALCON_VARIANT:-v5}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: ${PROJECT_PREFIX:-debugbar}-app
    hostname: ${PROJECT_PREFIX:-debugbar}-app
    volumes:
      - .:/srv
    env_file: .env
